name = "Additive Fork"
author = "Uranite"
version = "1.0.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24e4bb7ef899ececb7e6002089b461cd3d73c2dfe5349241c9ab822c9f55dedd"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
