name = "Additive Fork"
author = "Uranite"
version = "1.0.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffd8c939d4b55a4b100cbb1380a6d7420276d4df312db30ee83c5532778e3d39"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
