name = "Badly Optimized"
author = "Yiss"
version = "2.0.0+26.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fd13386263cea7590ecbae7816acd17c495385e6df434a430720e238aacc8d0"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
