name = "Badly Optimized"
author = "Yiss"
version = "2.0.0+26.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed8d9cea317c9166f6f9a46a3b68ea3d91f0101914f8daa86b4e99bf3f1aced5"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
