name = "Badly Optimized Voxy"
author = "Yiss"
version = "2.0.0+26.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a08164e8774f6ecb28644e15bb0433f43c14944fcd413ab67ca68e257ad8bb3a"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
