name = "Badly Optimized"
author = "Uranite"
version = "2.0.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "385a8692d1e8f0d1e595ebd878acb6ea6ed9b95bf74e226f2e418c34f97f9d9f"

[versions]
fabric = "0.18.6"
minecraft = "1.21.11"
