name = "Badly Optimized"
author = "Uranite"
version = "2.0.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e873b8131707b30aad1b5f7481c3b17183bc5e7276a136aa683ce97f7717354"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
