name = "Badly Optimized"
author = "Uranite"
version = "2.0.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90fae4cdc666835b9f4a66b3a43095d40e33f1f2e5282badf247c0c30f2b2f40"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
