name = "Badly Optimized"
author = "Yiss"
version = "2.0.0+26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8896b41bc1f8c3bf68704098389c3a2d7c24d40c64c995a73c3ee3b987ceeab6"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
