name = "Badly Optimized"
author = "Yiss"
version = "2.0.0+26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81261813a7e6bc51699d62853a09f86716acb11bc0c8c31336c7c8ede145a87c"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
