name = "Badly Optimized"
author = "Yiss"
version = "2.0.0+26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fb9e53f6bcdb929f9f2da06c259d0250700e0f6a64bf7e4855a50c1c88394c3"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
