name = "Badly Optimized"
author = "Uranite"
version = "2.0.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a41e0f867f33e2311cb9e91bc036b8269fccac8ad1439ed7de223de142ca6b01"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"
