name = "Badly Optimized"
author = "Uranite"
version = "2.0.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a9595087b41d2334d965a450c396002867043b6ad22cbd9ab85f7a5c726acb8"

[versions]
fabric = "0.19.2"
minecraft = "1.21.8"
