name = "Badly Optimized"
author = "Uranite"
version = "2.0.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "789e63b6a5c27b42520e76d5d29e52204099f0359d0451c86c1bc63eb496db37"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
