name = "Badly Optimized Test"
author = "Uranite"
version = "2.0.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e5094cd835567b44529901f73405cf02fa6520408b5745c6b35dc31d9d761a6"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
